package com.nnamanx.deliverymanagementsystem.enums;

public enum ExceptionMessage {
    USER_NOT_FOUND_EXCEPTION,
    CART_NOT_FOUND_EXCEPTION,
    CATEGORY_NOT_FOUND_EXCEPTION,
    CONFIRMATION_TOKEN_NOT_FOUND_EXCEPTION,
    EMAIL_NOT_FOUND_EXCEPTION,
    FOOD_NOT_FOUND_EXCEPTION,
    ORDER_NOT_FOUND_EXCEPTION,
    ROLE_NOT_FOUND_EXCEPTION,
    PASSWORD_TOKE_NOT_FOUND_EXCEPTION;

}
